 export const wwlMap = {

    "30": "In this course, you will explore all the key aspects of a filmmaking career that prepare you to become a responsible and professional filmmaker. You will learn how to manage your time efficiently, what tools and resources to bring to a film set, and how to determine your professional value. You will also understand how to effectively handle criticism and positively interact with your team. Additionally, you will learn strategies to secure your first opportunities in the industry.",
    "29": "In this course, you will learn how to effectively and systematically plan and prepare for a film, from pre-production to post-production, emphasizing the importance of each stage in achieving your artistic vision. You will gain a comprehensive understanding of how to create a detailed plan, starting from scriptwriting to managing the production team. Additionally, you will explore the MAFLAM platform and how to utilize it to access essential filmmaking resources.",
    "23": "In this course, you will learn how to generate creative ideas and transform them into a fully developed story. You'll master the art of building a strong plot, creating complex characters, and defining the central conflict and purpose of your narrative. The course will guide you through writing a treatment, structuring your screenplay, understanding different types of dialogue, and planning your scenes. You'll also learn how to craft your ideas into a written screenplay, preparing it for the big screen. Additionally, you will have access to downloadable worksheets for practical exercises to refine your skills. Key topics include constructing a scene, types of characters, creating conflict and purpose, understanding treatments and their types, writing dialogue, crafting a screenplay's conclusion, and revising for production purposes.",
    "21": "In this course, you will learn the fundamentals of film production and the crucial role of producers in filmmaking. You will master the financial aspects of production, including effective planning, budgeting, and creating detailed schedules. The course will also help you develop the essential skills to oversee the film at every stage, work with distributors, and safeguard the film's intellectual property rights. Additionally, you will cover other important details of production and have access to downloadable files and worksheets for practical exercises to enhance your learning. Key topics include the definition of a producer and their responsibilities, preparing and finalizing budgets, managing daily production orders on set, understanding the role of distributors, and the importance of contracts and how to write them.",
    "20": "In this course, you'll learn how to become a director and effectively manage a film set. You'll develop skills in selecting scripts and understanding key aspects of the preparation phase. The course will guide you through the process of choosing actors and communicating with them, as well as mastering the art of camera work, including understanding camera movements and creating impactful scenes. You'll also learn essential production management strategies to optimize each day of filming before moving into the editing phase. By the end, you'll grasp the foundational principles of directing that will allow you to professionally direct your first film. Key topics include the director's authority, camera language, the 30-degree and 180-degree rules, the differences between outdoor and studio shooting, and choosing the right soundtrack.",
    "25": "This course provides an in-depth explanation of camera mechanics, how to adjust settings, and the equipment used in conjunction with the camera, including when and how to use them. You’ll also explore light handling, angle selection, lens types, shot composition, exposure techniques, and more—ultimately equipping you with the skills of a director of photography.",
    "22": "In this course, you will explore the essential role of the sound engineer and the significant impact sound has on enhancing the cinematic experience. You will gain a thorough understanding of the tools and equipment used by sound engineers and learn how to analyze scripts to prevent mistakes during filming. The course will also cover the challenges sound engineers often face and provide effective strategies to overcome them. Key topics include the responsibilities of the sound team, different types of microphones and their uses, how recording devices operate, and techniques for managing echo in recording environments.",
    "24": "In this course, you will explore the concept of acting and its various schools while acquiring essential tools for becoming a skilled actor. Through exercises designed to enhance your acting talent, you will delve into the art of improvisation and learn its rules. The course will also guide you in creating harmony with fellow actors and mastering effective preparation techniques for filming scenes. Additionally, you will gain valuable insights into delivering powerful performances that captivate your audience. Key topics include different schools of acting, improvisation, practical tips for filming preparation, understanding acting contracts, and strategies for self-promotion as an actor.",
    "26": "In this course, you will grasp the fundamentals of video editing using Adobe Premiere Pro, including seamless transitions between scenes and adding visual effects and graphics. You'll also learn color correction techniques and audio engineering, as well as how to implement both basic and advanced animations. The course will provide you with a general understanding of editing techniques and how to export your film in high quality. Key Points You Will Learn in this Course: Cinematic editing techniques, Effective transition choices, Audio editing and mixing, Color correction techniques, Adding graphics and visuals, Utilizing effects for scene transitions, Finalizing and exporting your video in high quality.",
    "28": "In this course, you will discover the essential features of Vegas Pro, including how to create a new project, organize files, and effectively adjust segments. You will gain skills in adding effects and graphics, as well as working with both audio and video, along with a comprehensive understanding of editing principles. Key Points You Will Learn in this Course: Introduction to the software and how to download it, Understanding frame rates, Organizing files, Working with the timeline and using the toolbar, Splitting clips, Unique features of the software.",
    "27": "In this course, you will explore a variety of functions within DaVinci Resolve, including cutting, editing, merging, and coloring techniques. You will gain skills in using the media pool, adding effects and graphics, and professionally setting up your project. Additionally, you will learn how to adjust audio tracks and gain full control over all program options. Key Points You Will Learn in this Course: Understanding the editing tools in the software, Working on the timeline, Adding and editing audio and music, Incorporating effects and transitions, Color grading and correction, Assembling elements and exporting the film."
  };
  
 